image:
  repository: <your-ecr-repo-url> # e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/hello-world-app
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: LoadBalancer
  port: 80

container:
  port: 8080

ingress:
  enabled: true
  className: "alb"
  hosts:
    - host: myapp.example.com   # Use your domain or leave blank for wildcard
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi


